[tasks.clean]
command = "cargo"
args = ["clean", "--release"]

[tasks.build]
command = "cargo"
args = ["build", "--release"]
dependencies = ["clean"]

[tasks.sanitize]
script_runner = "@rust"
script = { file = "/post_build/sanitize.rs" }
dependencies = ["build"]

[tasks.flow]
dependencies = [
    "clean",
    "build",
    "sanitize"
]
